---
title: "BAN400 markdown"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
library(tidyquant)
library(tidyverse)
library(dplyr)
library(corrplot)
library(nloptr)
library(gtools)
library(skimr)
library(svDialogs)
library(TTR)
library(RColorBrewer)
library(htmlTable)



source("Ban400-Functions.R")



```



```{r }
risk_free_rate <- 0.02


tickers <- c("AAPL", "XOM", "BAC", "PFE", "NEE", "RTX", "GE", "REGN")
from_date <- "2018-01-01"
to_date <- "2020-05-01"


```





```{r}
tickers <- sample_function(5,filtered_industries = c("Aluminum"))

tickers

plot_industries(input[[1]],)



input <- input_function(tickers, from_date, to_date)


```







# input 1 = tickers
# input 2 = stock_prices
# input 3 = returns_matrix
# input 4 = stock_correlation
# input 5 = stock_return with date
# input 6 = stock_covariance
# input 7 = portfolio weigths
# input 8 = errors
# input 9 = stock info





```{r}
#finds the portfolio with the higest sharpe ratio
opt_sharpe <- stock_opt_sharpe(input[[1]],input[[7]],input[[3]],input[[6]])
opt_sharpe[[3]]

#finds the portfolio with the lowest yearly volatility
opt_vol <- stock_opt_vol(input[[1]],input[[7]],input[[3]],input[[6]])
opt_vol[[4]]

#find the portfolio with the higest sortino ratio
opt_sortino <- stock_opt_sortino(input[[1]],input[[7]],input[[3]],input[[6]])
opt_sortino[[1]]


#creates returns histogram
returns_hist(input[[5]])
#creates correlation matrix
correlation_plot(input[[4]])

# creates stock price history graph
stock_price_history(input[[2]])

#Creates effeciency frontier
efficency_frontier(input[[1]],input[[7]],input[[3]],input[[6]], n = 5000)



#plot optimal portfolio industry composition
portfolio_industry(input[[1]], opt_sharpe[[2]])


#tests the optimised portfolio vs the S&P500 index


compare_SP500((opt_vol[[2]]),input[[1]],from_date,to_date)

```

```{r}

tickers = input[[1]]
weigths = input[[7]]
returns = input[[3]]
cov_matrix = input[[6]]

returns %*% weigths

#finds the prtofolio with the optimal sharpe ratio
stock_opt_sharpe <- function(tickers, weigths ,returns,cov_matrix,  upper_bounds = 1, 
                             lower_bounds = 0, port_size = 1) {
  
  weigths = weigths
  bounds <- c(rep(upper_bounds,length(weigths)))
  lower_bounds = c(rep(lower_bounds,length(weigths)))
  
  con <- function(weigths){
    port <-weigths
    return(sum(port)-port_size) }
  nl.opts(list(xtol_rel = 0,ftol_abs = 0.0, maxeval = 10000))
  
  sharpe <- slsqp(weigths, fn = neg_sharpe(weigths,returns,cov_matrix), lower = lower_bounds,
                  upper = bounds, heq = con)
  
  max_sharpe_port <- as.data.frame(t(round(sharpe$par,4)))
  colnames(max_sharpe_port) <- tickers
  Max_sharpe <- port_summary(sharpe$par,returns,cov_matrix)
  
  stocks <- as.data.frame(t(max_sharpe_port)) %>% 
  arrange(desc(V1)) %>% 
  filter(V1>0) %>% 
  mutate(Symbol = row.names(.)) %>%  
  left_join(stock_info, by=c("Symbol"="Symbol")) %>% 
  rename("Percentage" = "V1") %>% 
  select(Percentage, Name, Symbol)
  stocks <- htmlTable(stocks)
  
  
  max_sharpe_port$Sharpe_ratio = Max_sharpe$Sharpe_ratio
  max_sharpe_port$Yearly_std = Max_sharpe$Yearly_std
  max_sharpe_port$mean_return = Max_sharpe$Avg_yearly_return
  max_sharpe_port$Yearly_std = Max_sharpe$Yearly_std
  
  result <- list(max_sharpe_port, sharpe$par, stocks)
  
  return(result)
}


stocks <- as.data.frame(t(max_sharpe_port)) %>% 
  arrange(desc(V1)) %>% 
  filter(V1>0) %>% 
  mutate(Symbol = row.names(.)) %>%  
  left_join(stock_info, by=c("Symbol"="Symbol")) %>% 
  rename("Percentage" = "V1") %>% 
  select(Percentage, Name, Symbol)

stocks <- htmlTable(stocks)


testz <- grep("Tobacco", stocks_with_industry$Industry, ignore.case = T)

stocks_with_industry[4538,]


grep("MO", stocks_with_industry$Symbol, fixed = T, value = T)


library(rvest)

simple <- read_html("https://sinstocksreport.com/list-of-sin-stocks/")
simple <- simple %>% 
  html_nodes("li") %>% 
  html_text()

sin.stocks <- simple[14:149]
sin.stocks <- as.data.frame(sin.stocks)

sin.stocks <- separate(sin.stocks, col = sin.stocks, into = c("Name","x2"), sep = "\\(") 
sin.stocks <- separate(sin.stocks, col = x2, into = c("x2", "Symbol"), sep = "\\:") 
sin.stocks <- separate(sin.stocks, col = Symbol, into = c("Symbol","x4"), sep = "\\)") 
sin.stocks <- subset(sin.stocks, select = -c(x2, x4))


sin.stocks %>% 
  inner_join(stocks_with_industry, by =c("Symbol"="Symbol"))


test <- (sin.stocks$Symbol %in% stocks_with_industry$Symbol)

test <- sin.stocks$Symbol

test <- str_replace(test, " ", "")
  


sin.stocks <- stocks_with_industry %>% 
  filter(Symbol %in% test)




```


```{r}

library(readxl)

green <- read_excel("renewablestocks.xlsx")
green <- green %>% 
  select(Symbol) %>% 
  mutate(ethics = "Marked as green stock")

sin <- read_excel("sinstocks.xlsx")
sin <- sin %>% 
  select(Symbol) %>% 
  mutate(ethics = "marked as unethical")

test <-stocks_with_industry %>% 
  left_join(sin, by = c("Symbol"= "Symbol")) %>% 
  inner_join(green, by = c("Symbol" = "Symbol")) %>% 
  replace_na(list(ethics = "netrual"))


test <- (green$Symbol %in% stocks_with_industry$Symbol)
test

grep("TSLA", stocks_with_industry$Symbol)
skim(test)

grep(paste(green$Symbol, sep = "|", collapse = ""), green$Symbol)

paste(green$Symbol, sep = "|", collapse = "")

grep

```


```{r}
#creates a histogram of the returns of portfolio
returns_final_hist <- function(returns_matrix,weights) {
  
  skew <- round(skewness(returns_matrix%*%weights),3)
  kurtosis <- round(kurtosis(returns_matrix%*%weights),3)
 
  ret_final_hist <- as.data.frame(returns_matrix%*%weights) %>%
    ggplot(aes(x = V1))+
    geom_histogram(bins = 40, col = "black", fill = "steelblue")+
    theme_classic() +
    xlab("Returns") +
    ylab("Count") +
    theme(plot.title = element_text(color = "black"))+
    labs(title = "Portfolio returns histogram", subtitle = paste("skewness: ", skew, ",  ", "kurtosis: ", kurtosis))
  return(ret_final_hist)
}

hist <- returns_final_hist(input[[3]],input[[7]])
hist 

```

